wip APIからデータ取得して表示した
Yoshitsugu-Antony-Kambara/cta_reactive_master pull request #3
Opened 2020-12-05 11:35 UTC by Yoshitsugu-Antony-Kambara

## 関連するIssues

## 行ったこと
- 

## 変更内容

| Before | After |
| --- | --- |
|  |  |

## 参考
- 

## その他 補足
-

2020-12-08 13:11 UTC, tomu28 requested changes
いったん、対応が必須の箇所のみレビューしました！

2020-12-08 13:11 UTC, tomu28 commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +                self.table.reloadData()
[MUST]
この処理をmainスレッドで行うように修正しよう👍

2020-12-08 13:11 UTC, tomu28 commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        AF.request("https://newsapi.org/v2/top-headlines?country=us&apiKey=583fb19028bd4ef688432161cd5cc0fd")
[MUST]
1. apikeyは.ignoreしよう
2. `country=us`の`us`などは変数化して変更しやすいURLパラメータにしよう

2020-12-08 13:11 UTC, tomu28 commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        print("start")
[NITS]
不要なprintは削除するようにしよう
`// TODO 動作確認が出来たら削除する`
みたいなコメントを付けておくのも良いね👍

2020-12-08 13:11 UTC, tomu28 commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    func getArticles() {
[MUST]
APIを取得する`getArticles`はViewControllerで行うべきではないので、
APIClientといったクラスorStructを作成し、そちらで処理を行うよう出来ると🙆‍♂️

2020-12-08 13:11 UTC, tomu28 commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +import Alamofire
APIClient以外は`import Alamofire ` を行わない仕組みが理想だねd(^_^o)

2020-12-19 11:42 UTC, Yoshitsugu-Antony-Kambara commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        AF.request("https://newsapi.org/v2/top-headlines?country=us&apiKey=583fb19028bd4ef688432161cd5cc0fd")
(ac0ceaf)country = us のusを変数化した

2020-12-19 12:03 UTC, Yoshitsugu-Antony-Kambara commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        AF.request("https://newsapi.org/v2/top-headlines?country=us&apiKey=583fb19028bd4ef688432161cd5cc0fd")
(39c4649)APIkeyを.ignoreした

2020-12-19 12:19 UTC, Yoshitsugu-Antony-Kambara commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        print("start")
(0b8b1ba)不要なprintを削除

2020-12-19 12:21 UTC, Yoshitsugu-Antony-Kambara commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +                self.table.reloadData()
(c6910b1)mainスレッドで行うようにした

2021-09-16 19:54 UTC, merged